# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they have a “cow”.
# For every digit the user guessed correctly in the wrong place is a “bull.”
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
# Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.
import random


def cows_and_bulls():
    four_digit_str = str(random.randint(1000,9999))
    print(four_digit_str)
    number_of_guesses = 0


    while True:
        cow = 0
        bull = 0
        guess = str(input("Guess a 4-digit number.: "))
        for i in range(4):
            if four_digit_str == guess:
                cow = 4
            elif four_digit_str[i] in guess[i]:
                cow = cow + 1
            elif four_digit_str[i] in guess:
                bull = bull + 1
        number_of_guesses += 1
        if cow <4:
            print(f"{cow} cows, {bull} bulls")

        elif cow == 4:
            print()
            print("!You win! {^V^}____/   {^o^}____/ {*.*}____/ {o.o}____/")
            print(" 4 cows     {______}     {______}   {______}   {______}")
            print("            /|    ||     /|    ||   /|    ||   /|    ||")
            print(f"Number of guesses:{number_of_guesses}")
            exit()




cows_and_bulls()